### ISSUE TITLE
Tampilan user yang tidak sesuai dengan yang dipilih!

### ISSUE THREAD

**Issue by riantopangaribuan** [CoderJava/dipantau-desktop#3]
Ketika memilih user paling bawah (misalnya), yang tampil tetap user paling atas, seharusnya langsung menampilkan user yang sedang dipilih
<img width="661" alt="image" src="https://github.com/CoderJava/dipantau-desktop/assets/69283861/8e5dbfbd-4567-4739-a964-92656a38bd55">
<img width="688" alt="image" src="https://github.com/CoderJava/dipantau-desktop/assets/69283861/9415b5c1-3e63-4073-8b2b-1b15acd3614a">

**Comment by CoderJava** [comment]
Setelah dicek, itu awalnya menggunakan dialog untuk menampilkan pilihan user-nya. Dan ternyata didalam dialog tersebut belum ada fitur untuk keep position scroll-nya berdasarkan item yang terpilih.

Jadi, solusinya adalah ubah saja widget-nya dari dialog menjadi dropdown seperti ini.

https://github.com/CoderJava/dipantau-desktop/assets/17062085/c2d5f549-f120-43f1-8624-aca0b693d659

**Comment by CoderJava** [comment]
Sudah di release di versi [1.2.0](https://github.com/CoderJava/dipantau-desktop/releases/tag/v1.2.0).
